server:
  port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${conf:https://github.com/avitkinov/spring-cloud-config}
          
encrypt:
  key: 0123456789abcdef
